### PR TITLE
Enable run/build scripts to run on MacOS

### PR DESCRIPTION
**Pull request by kivarsson-va**
The setup scripts weren't working when run on a mac so we put in OS checks to run slightly different commands for mac users.

As always please let us know if there are any issues!

### CODE REVIEW

**Comment by bschofield-va** [comment]
Let me think about this ... all Shanktopus runs macOs.

**Comment by kivarsson-va** [comment]
> Let me think about this ... all Shanktopus runs macOs.

okay interesting.. the script wasn't running out of the box for us (actually, most of the scripts across repos aren't) and when we dug a bit deeper the most likely reason seemed to be an OS issue with some of the commands

we're happy to pair on anything if that's helpful. let us know!

**Comment by kivarsson-va** [comment]
@bschofield-va do y'all alias any of the commands you're running in your scripts?

**Comment by kivarsson-va** [comment]
@bschofield-va that script still doesn't run for us.

is it standard across Lighthouse to set up your environments to mimic Linux? or just something your team has done? It might be easier for us to just copy your local env instead of trying to mess with all of these build scripts -- do y'all have any documentation on that?

**Pull request closed without merging**
