### PR TITLE
API 10406 Immunization Schema CompositeCdwId Update

### PR DESCRIPTION
**Pull request by that-guy-is-it**
@nmoisan @jtaylor-va @haidong pinging since this is a schema update!

### CODE REVIEW

**Review by jtaylor-va — DISMISSED** [review]
LGTM!

**Review by jblefkove-va — APPROVED** [review]
:shipit:

**Review by jblefkove-va — CHANGES_REQUESTED** [review]
Change version to `21_1`

**Review by jblefkove-va — APPROVED** [review]
:shipit:

**Pull request merged**
